gui:
  showIcons: true
  theme:
    activeBorderColor:
      - magenta
      - bold
    inactiveBorderColor:
      - black
  showFileTree: true # for rendering changes files in a tree format
os:
  edit: "nvim"
keybinding:
  universal:
    quit: "q"
